### ISSUE TITLE
Mouse position incorrect when holding ctrl+shift on HiDPI screens

### ISSUE THREAD

**Issue by Arokha** [monster860/FastDMM2#11]
A comparison between normal mouse movement when not holding modifiers.

No modifiers:
![image](https://user-images.githubusercontent.com/15028025/83200599-ac923380-a111-11ea-9635-977ce982880d.png)

Ctrl-shift:
![image](https://user-images.githubusercontent.com/15028025/83200623-be73d680-a111-11ea-8b4f-9fef35643ec0.png)
(The left door is highlighted)

**Comment by martinlyra** [comment]
Gonna ride off this one as I believe these issues are related as well.

It might be worth to mention that on Firefox, using export will open a bar at bottom of the window, which shrinks the viewport. As result, the cursor receives an offset equal the height of the download bar opened as well.

Here's an example using the console to replicate the effect with exaggeration. 
![bild](https://user-images.githubusercontent.com/13331724/84379773-a8bce180-abe6-11ea-9576-45f067735e3f.png)
Console opened:
![bild](https://user-images.githubusercontent.com/13331724/84379873-cdb15480-abe6-11ea-96ba-e9d265ad8c64.png)
