### ISSUE TITLE
TypeError?

### ISSUE THREAD

**Issue by Marmio64** [monster860/FastDMM2#17]
As of today I just tried to use fastdmm2 and when I attempt to pull up yogstation it says 'TypeError:e.values(...)is not a function or its return value is not asynciterable'

This never happened before, and I haven't changed anything, so I don't know what happened.

**Comment by monster860** [comment]
Make sure you are using the latest version of Chrome

**Comment by Marmio64** [comment]
> Make sure you are using the latest version of Chrome (Chrome 86)

yeah that fixed it, thanks
