### ISSUE TITLE
Unable to log into GitHub 

### ISSUE THREAD

**Issue by Tennessee116** [monster860/FastDMM2#23]
Whenever I attempt to use the Log Into Github button, it attempts to authorize and quickly redirects to a blank page, https://fastdmm2.ss13.io/gh_callback.html. I can provide more details if nessecary.

**Comment by monster860** [comment]
I have resolved the issue I believe

**Comment by Tennessee116** [comment]
> I have resolved the issue I believe

Indeed you have, now it works.
